<?php

declare(strict_types=1);

namespace EzPhp\Ai\Message;

/**
 * Message role in a conversation turn.
 */
enum Role: string
{
    /** A message sent by the end user. */
    case USER = 'user';

    /** A message generated by the AI model. */
    case ASSISTANT = 'assistant';

    /** High-level instructions that frame the model's behaviour. */
    case SYSTEM = 'system';

    /** The result of a tool/function call, fed back to the model. */
    case TOOL = 'tool';
}
