<?php

declare(strict_types=1);

namespace EzPhp\Ai\Response;

/**
 * Immutable token-usage report from an AI provider response.
 *
 * @package EzPhp\Ai\Response
 */
final readonly class TokenUsage
{
    /**
     * @param int $inputTokens  Tokens consumed by the prompt / input messages.
     * @param int $outputTokens Tokens generated by the model.
     */
    public function __construct(
        private int $inputTokens,
        private int $outputTokens,
    ) {
    }

    /**
     * @return int
     */
    public function inputTokens(): int
    {
        return $this->inputTokens;
    }

    /**
     * @return int
     */
    public function outputTokens(): int
    {
        return $this->outputTokens;
    }

    /**
     * Combined input and output token count.
     *
     * @return int
     */
    public function totalTokens(): int
    {
        return $this->inputTokens + $this->outputTokens;
    }
}
